# Generated by Django 5.2.3 on 2025-12-15 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculumId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('effectiveSy', models.CharField(max_length=20)),
                ('dean', models.CharField(blank=True, max_length=100, null=True)),
                ('vicePresidentForAcademicAffairs', models.CharField(blank=True, max_length=100, null=True)),
                ('universityPresident', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomId', models.AutoField(primary_key=True, serialize=False)),
                ('roomCode', models.CharField(max_length=20)),
                ('building', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(choices=[('lecture', 'Lecture'), ('laboratory', 'Laboratory')], max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionId', models.AutoField(primary_key=True, serialize=False)),
                ('sectionCode', models.CharField(max_length=50)),
                ('numberOfStudents', models.IntegerField(default=0)),
                ('units', models.IntegerField()),
                ('lectureMinutes', models.IntegerField()),
                ('hasLab', models.BooleanField(default=False)),
                ('labMinutes', models.IntegerField(default=0)),
                ('isPriorityForRooms', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('dayOfWeek', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('scheduleType', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab')], max_length=10)),
                ('isOvertime', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('finalized', 'Finalized')], default='active', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.section')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('pendingApproval', 'Pending Approval'), ('finalized', 'Finalized')], max_length=30)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.schedule')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('academicYear', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('Midyear', 'Midyear')], max_length=10)),
                ('isActive', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('normalDays', models.JSONField(blank=True, default=list, help_text='Days considered normal class days (Mon-Fri)', null=True)),
                ('weekendAllowed', models.BooleanField(default=True, help_text='Allow Sat/Sun classes if weekdays insufficient')),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.curriculum')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester'),
        ),
        migrations.CreateModel(
            name='GenEdSchedule',
            fields=[
                ('genedScheduleId', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('subjectName', models.CharField(max_length=100)),
                ('sectionCode', models.CharField(max_length=10)),
                ('instructorName', models.CharField(blank=True, max_length=100, null=True)),
                ('dayOfWeek', models.CharField(max_length=10)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('isPriority', models.BooleanField(default=True, help_text='If True, IT schedules must adjust around this')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('units', models.IntegerField()),
                ('durationMinutes', models.IntegerField()),
                ('defaultTerm', models.IntegerField(choices=[(0, '1st'), (1, '2nd'), (2, 'Midyear')])),
                ('yearLevel', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')])),
                ('hasLab', models.BooleanField(default=False)),
                ('labDurationMinutes', models.IntegerField(blank=True, null=True)),
                ('isPriorityForRooms', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subjectTopics', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='scheduling.curriculum')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject'),
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultStudentsPerSection', models.IntegerField(default=40)),
                ('numberOfSections', models.PositiveIntegerField(default=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='scheduling.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='scheduling.subject')),
            ],
            options={
                'unique_together': {('subject', 'semester')},
            },
        ),
    ]
