# Generated by Django 5.2.3 on 2025-07-29 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_subject_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectoffering',
            old_name='offerId',
            new_name='offeringId',
        ),
        migrations.RemoveField(
            model_name='subjectoffering',
            name='match',
        ),
        migrations.RemoveField(
            model_name='subjectoffering',
            name='sectionCode',
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='scheduling.semester'),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='scheduling.subject'),
        ),
    ]
