# Generated by Django 5.2.3 on 2025-07-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_genedschedule_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Import',
        ),
    ]
