# Generated by Django 5.2.3 on 2025-07-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_rename_offerid_subjectoffering_offeringid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='offer',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject'),
            preserve_default=False,
        ),
    ]
