# Generated by Django 5.2.3 on 2025-07-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_remove_user_role_user_roles'),
        ('scheduling', '0003_delete_import'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'subject', 'section')},
        ),
    ]
