# Generated by Django 5.2.3 on 2025-07-29 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_remove_schedule_offer_schedule_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectOffering',
        ),
    ]
