# Generated by Django 5.2.3 on 2025-07-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_delete_subjectoffering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
