# Generated by Django 5.2.3 on 2025-07-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_semester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subjectTopics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
