# Generated by Django 5.2.3 on 2025-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_delete_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedschedule',
            name='isPriority',
            field=models.BooleanField(default=True, help_text='If True, IT schedules must adjust around this'),
        ),
    ]
