# Generated by Django 5.2.3 on 2025-07-19 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_subject_subjecttopics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
