# Generated by Django 5.2.3 on 2025-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_genedschedule_ispriority'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalStartTime', models.TimeField(default='08:00')),
                ('normalEndTime', models.TimeField(default='17:00')),
                ('overtimeEndTime', models.TimeField(default='20:00')),
                ('allowWeekends', models.BooleanField(default=True)),
                ('maxSectionsPerSubject', models.IntegerField(default=5)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
