# Generated by Django 5.2.3 on 2025-07-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='createdAt',
            new_name='enrollmentDate',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='subject',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduling.schedule'),
            preserve_default=False,
        ),
    ]
