# Generated by Django 5.2.3 on 2025-07-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_schedulingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='normalDays',
            field=models.JSONField(blank=True, default=list, help_text='Days considered normal class days (Mon-Fri)', null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='weekendAllowed',
            field=models.BooleanField(blank=True, default=True, help_text='Allow Sat/Sun classes if weekdays insufficient', null=True),
        ),
    ]
