# Generated by Django 5.2.3 on 2025-07-31 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_semester_normaldays_semester_weekendallowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingconfig',
            name='normalEndTime',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='schedulingconfig',
            name='normalStartTime',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='schedulingconfig',
            name='overtimeEndTime',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
    ]
