# Generated by Django 5.2.3 on 2025-07-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_schedulingconfig_normalendtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sectionCount',
            field=models.IntegerField(blank=True, default=1, help_text='Number of sections to open', null=True),
        ),
    ]
