# Generated by Django 5.2.3 on 2025-07-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_rename_haslabcomponent_subject_haslab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='defaultTerm',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('Midyear', 'Midyear')], max_length=10),
        ),
    ]
