# Generated by Django 5.2.3 on 2025-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_alter_subject_defaultterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='defaultTerm',
            field=models.IntegerField(choices=[(0, '1st'), (1, '2nd'), (2, 'Midyear')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='subject',
            name='yearLevel',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')]),
        ),
    ]
