# Generated by Django 5.2.3 on 2025-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_subject_sectioncount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='weekendAllowed',
            field=models.BooleanField(default=True, help_text='Allow Sat/Sun classes if weekdays insufficient'),
        ),
    ]
