# Generated by Django 5.2.3 on 2025-07-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='scheduling.curriculum'),
            preserve_default=False,
        ),
    ]
