# Generated by Django 5.2.3 on 2025-07-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_alter_schedule_dayofweek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchedulingConfig',
        ),
    ]
