# Generated by Django 5.2.3 on 2025-07-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_subject_curriculum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorSubjectMatchHistory',
        ),
    ]
