# Generated by Django 5.2.3 on 2025-08-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_subjectoffering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectOffering',
        ),
    ]
