# Generated by Django 5.2.3 on 2025-07-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_delete_instructorsubjectmatchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectoffering',
            name='match',
        ),
        migrations.DeleteModel(
            name='InstructorSubjectMatch',
        ),
    ]
