# Generated by Django 5.2.3 on 2025-08-03 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_delete_subjectoffering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfSections', models.PositiveIntegerField(default=1)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='scheduling.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='scheduling.subject')),
            ],
            options={
                'unique_together': {('subject', 'semester')},
            },
        ),
    ]
