# Generated by Django 5.2.3 on 2025-07-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0004_instructorsubjectmatch'),
        ('scheduling', '0016_remove_subjectoffering_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectoffering',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aimatching.instructorsubjectmatch'),
            preserve_default=False,
        ),
    ]
