# Generated by Django 5.2.3 on 2025-08-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_subjectoffering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sectionCount',
        ),
    ]
