# Generated by Django 5.2.3 on 2025-08-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_remove_schedule_schedulestatus_schedule_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedschedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
