# Generated by Django 5.2.3 on 2025-08-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_genedschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectoffering',
            name='numberOfSections',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
