# Generated by Django 5.2.3 on 2025-08-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0021_alter_subjectoffering_numberofsections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sectionCode',
            field=models.CharField(max_length=50),
        ),
    ]
