# Generated by Django 5.2.3 on 2025-12-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorSubjectMatch',
            fields=[
                ('matchId', models.AutoField(primary_key=True, serialize=False)),
                ('isRecommended', models.BooleanField(default=True)),
                ('isLatest', models.BooleanField(default=True)),
                ('batchId', models.CharField(max_length=100)),
                ('modelVersion', models.CharField(blank=True, max_length=50, null=True)),
                ('generatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generatedAt'],
            },
        ),
        migrations.CreateModel(
            name='InstructorSubjectMatchHistory',
            fields=[
                ('historyId', models.AutoField(primary_key=True, serialize=False)),
                ('confidenceScore', models.FloatField()),
                ('experienceScore', models.FloatField()),
                ('teachingScore', models.FloatField()),
                ('credentialScore', models.FloatField()),
                ('preferenceScore', models.FloatField(default=0.0)),
                ('primaryFactor', models.CharField(max_length=50)),
                ('previousMatchScore', models.FloatField(blank=True, null=True)),
                ('scoreChange', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('modelVersion', models.CharField(blank=True, max_length=50, null=True)),
                ('batchId', models.CharField(max_length=100)),
                ('generatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingConfig',
            fields=[
                ('configId', models.AutoField(primary_key=True, serialize=False)),
                ('teachingWeight', models.FloatField(default=0.2)),
                ('credentialsWeight', models.FloatField(default=0.3)),
                ('experienceWeight', models.FloatField(default=0.3)),
                ('preferenceWeight', models.FloatField(default=0.2)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingProgress',
            fields=[
                ('batchId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('totalTasks', models.IntegerField(default=0)),
                ('completedTasks', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('startedAt', models.DateTimeField(auto_now_add=True)),
                ('finishedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingRun',
            fields=[
                ('runId', models.AutoField(primary_key=True, serialize=False)),
                ('batchId', models.CharField(max_length=100, unique=True)),
                ('totalSubjects', models.IntegerField()),
                ('totalInstructors', models.IntegerField()),
                ('generatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
