# Generated by Django 5.2.3 on 2025-07-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorSubjectMatch',
            fields=[
                ('matchId', models.AutoField(primary_key=True, serialize=False)),
                ('matchScore', models.FloatField()),
                ('matchLevel', models.IntegerField()),
                ('primaryFactor', models.CharField(max_length=50)),
                ('experienceScore', models.FloatField()),
                ('teachingScore', models.FloatField()),
                ('credentialScore', models.FloatField()),
                ('availabilityScore', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('modelVersion', models.CharField(blank=True, max_length=50, null=True)),
                ('generatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-matchScore'],
            },
        ),
        migrations.CreateModel(
            name='InstructorSubjectMatchHistory',
            fields=[
                ('matchId', models.AutoField(primary_key=True, serialize=False)),
                ('confidenceScore', models.FloatField()),
                ('primaryFactor', models.CharField(max_length=50)),
                ('experienceScore', models.FloatField()),
                ('teachingScore', models.FloatField()),
                ('credentialScore', models.FloatField()),
                ('availabilityScore', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('generatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
