# Generated by Django 5.2.3 on 2025-12-15 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aimatching', '0001_initial'),
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='generatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor'),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject'),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='generatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor'),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject'),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='latestHistory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_match', to='aimatching.instructorsubjectmatchhistory'),
        ),
        migrations.AddField(
            model_name='matchingconfig',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester'),
        ),
        migrations.AddField(
            model_name='matchingprogress',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchingprogress',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester'),
        ),
        migrations.AddField(
            model_name='matchingrun',
            name='generatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchingrun',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester'),
        ),
    ]
