# Generated by Django 5.2.3 on 2025-07-21 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0001_initial'),
        ('core', '0004_instructor_designation_instructor_rank'),
        ('scheduling', '0015_delete_instructorsubjectmatchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstructorSubjectMatchHistory',
            new_name='InstructorSubject',
        ),
    ]
