# Generated by Django 5.2.3 on 2025-07-23 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aimatching', '0001_initial'),
        ('core', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='generatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor'),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject'),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='generatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor'),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='instructorsubjectmatch',
            unique_together={('instructor', 'subject')},
        ),
    ]
