# Generated by Django 5.2.3 on 2025-07-21 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0002_rename_instructorsubjectmatchhistory_instructorsubject'),
        ('core', '0004_instructor_designation_instructor_rank'),
        ('scheduling', '0016_remove_subjectoffering_match_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstructorSubject',
            new_name='InstructorSubjectMatchHistory',
        ),
    ]
