# Generated by Django 5.2.3 on 2025-07-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructorsubjectmatch',
            unique_together=set(),
        ),
    ]
