# Generated by Django 5.2.3 on 2025-07-21 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0003_rename_instructorsubject_instructorsubjectmatchhistory'),
        ('core', '0004_instructor_designation_instructor_rank'),
        ('scheduling', '0016_remove_subjectoffering_match_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorSubjectMatch',
            fields=[
                ('matchId', models.AutoField(primary_key=True, serialize=False)),
                ('confidenceScore', models.FloatField()),
                ('primaryFactor', models.CharField(max_length=50)),
                ('experienceScore', models.FloatField()),
                ('teachingScore', models.FloatField()),
                ('credentialScore', models.FloatField()),
                ('availabilityScore', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('generatedAt', models.DateTimeField(auto_now_add=True)),
                ('generatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject')),
            ],
        ),
    ]
