# Generated by Django 5.2.3 on 2025-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0003_alter_instructorsubjectmatch_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorsubjectmatch',
            options={'ordering': ['-generatedAt']},
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='batchId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='isLatest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='isRecommended',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='matchReason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='previousMatchScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='scoreChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='batchId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='previousMatchScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='scoreChange',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
