# Generated by Django 5.2.3 on 2025-07-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0004_alter_instructorsubjectmatch_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorsubjectmatchhistory',
            old_name='notes',
            new_name='explanation',
        ),
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='modelVersion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
