# Generated by Django 5.2.3 on 2025-07-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0004_instructorsubjectmatch'),
        ('core', '0004_instructor_designation_instructor_rank'),
        ('scheduling', '0017_subjectoffering_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorsubjectmatch',
            options={'ordering': ['-score']},
        ),
        migrations.AlterUniqueTogether(
            name='instructorsubjectmatch',
            unique_together={('instructor', 'subject')},
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='confidenceScore',
        ),
    ]
