# Generated by Django 5.2.3 on 2025-07-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0005_alter_instructorsubjectmatch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorsubjectmatch',
            options={'ordering': ['-matchScore']},
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='score',
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='matchLevel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='matchScore',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
