# Generated by Django 5.2.3 on 2025-07-29 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0005_rename_notes_instructorsubjectmatchhistory_explanation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorsubjectmatchhistory',
            old_name='matchId',
            new_name='historyId',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='availabilityScore',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='credentialScore',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='experienceScore',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='matchLevel',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='matchReason',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='matchScore',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='previousMatchScore',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='primaryFactor',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='scoreChange',
        ),
        migrations.RemoveField(
            model_name='instructorsubjectmatch',
            name='teachingScore',
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='latestHistory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_match', to='aimatching.instructorsubjectmatchhistory'),
        ),
    ]
