# Generated by Django 5.2.3 on 2025-07-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0006_rename_matchid_instructorsubjectmatchhistory_historyid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
