# Generated by Django 5.2.3 on 2025-07-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0006_alter_instructorsubjectmatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorsubjectmatch',
            name='modelVersion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
