# Generated by Django 5.2.3 on 2025-07-29 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0007_instructorsubjectmatchhistory_rank'),
        ('scheduling', '0002_subject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingConfig',
            fields=[
                ('configId', models.AutoField(primary_key=True, serialize=False)),
                ('teachingWeight', models.FloatField(default=0.2)),
                ('credentialWeight', models.FloatField(default=0.3)),
                ('experienceWeight', models.FloatField(default=0.3)),
                ('preferenceWeight', models.FloatField(default=0.2)),
                ('threshold', models.FloatField(default=0.6)),
                ('modelVersion', models.CharField(default='CrossEncoder-msmarco-v1', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester')),
            ],
        ),
    ]
