# Generated by Django 5.2.3 on 2025-07-29 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0008_matchingconfig'),
        ('scheduling', '0002_subject_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRun',
            fields=[
                ('runId', models.AutoField(primary_key=True, serialize=False)),
                ('batchId', models.CharField(max_length=100, unique=True)),
                ('totalSubjects', models.IntegerField()),
                ('totalInstructors', models.IntegerField()),
                ('generatedAt', models.DateTimeField(auto_now_add=True)),
                ('generatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester')),
            ],
        ),
    ]
