# Generated by Django 5.2.3 on 2025-07-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0009_matchingrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorsubjectmatchhistory',
            name='availabilityScore',
        ),
    ]
