# Generated by Django 5.2.3 on 2025-07-29 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0010_remove_instructorsubjectmatchhistory_availabilityscore'),
        ('scheduling', '0002_subject_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchingconfig',
            old_name='credentialWeight',
            new_name='credentialsWeight',
        ),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='active',
        ),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='modelVersion',
        ),
        migrations.RemoveField(
            model_name='matchingconfig',
            name='threshold',
        ),
        migrations.AlterField(
            model_name='matchingconfig',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester'),
        ),
    ]
