# Generated by Django 5.2.3 on 2025-07-29 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0011_rename_credentialweight_matchingconfig_credentialsweight_and_more'),
        ('scheduling', '0002_subject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingProgress',
            fields=[
                ('batchId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('totalTasks', models.IntegerField(default=0)),
                ('completedTasks', models.IntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('startedAt', models.DateTimeField(auto_now_add=True)),
                ('finishedAt', models.DateTimeField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester')),
            ],
        ),
    ]
