# Generated by Django 5.2.3 on 2025-07-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0012_matchingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorsubjectmatchhistory',
            name='preferenceScore',
            field=models.FloatField(default=0.0),
        ),
    ]
