# Generated by Django 5.2.3 on 2025-07-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimatching', '0013_instructorsubjectmatchhistory_preferencescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorsubjectmatchhistory',
            name='rank',
        ),
    ]
