# Generated by Django 5.2.3 on 2025-07-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_remove_user_role_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
