# Generated by Django 5.2.3 on 2025-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='acronym',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='acronym',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
