# Generated by Django 5.2.3 on 2025-07-23 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('instructors', '0004_instructoracademicattainment'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='academicAttainment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructoracademicattainment'),
        ),
    ]
