# Generated by Django 5.2.3 on 2025-07-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instructor_academicattainment'),
        ('instructors', '0010_alter_instructorcredentials_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='academicAttainment',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='designation',
        ),
        migrations.AddField(
            model_name='instructor',
            name='designations',
            field=models.ManyToManyField(blank=True, to='instructors.instructordesignation'),
        ),
    ]
