# Generated by Django 5.2.3 on 2025-07-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instructor_updatedat'),
        ('instructors', '0015_instructorrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructordesignation'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructorrank'),
        ),
    ]
