# Generated by Django 5.2.3 on 2025-07-31 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_instructor_academicattainment_and_more'),
        ('instructors', '0010_alter_instructorcredentials_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='designations',
        ),
        migrations.AddField(
            model_name='instructor',
            name='academicAttainment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructoracademicattainment'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='designation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructordesignation'),
        ),
    ]
