# Generated by Django 5.2.3 on 2025-07-31 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_instructor_designations_and_more'),
        ('instructors', '0010_alter_instructorcredentials_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='academicAttainment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructoracademicattainment'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructordesignation'),
        ),
    ]
