# Generated by Django 5.2.3 on 2025-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_instructor_academicattainment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='normalLoad',
            field=models.IntegerField(default=18, help_text='Max units/hours under normal load'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='overLoad',
            field=models.IntegerField(default=6, help_text='Extra units/hours allowed as overload'),
        ),
    ]
