# Generated by Django 5.2.3 on 2025-07-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_instructor_normalload_instructor_overload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='normalLoad',
            field=models.IntegerField(blank=True, default=18, help_text='Max units/hours under normal load', null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='overLoad',
            field=models.IntegerField(blank=True, default=6, help_text='Extra units/hours allowed as overload', null=True),
        ),
    ]
