# Generated by Django 5.2.3 on 2025-08-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('auditId', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('targetTable', models.CharField(max_length=100)),
                ('targetId', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('errorMessage', models.TextField(blank=True, null=True)),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationId', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('notificationType', models.CharField(choices=[('system', 'System'), ('message', 'Message'), ('reminder', 'Reminder'), ('scheduleUpdate', 'Schedule Update')], default='system', max_length=50)),
                ('referenceId', models.CharField(blank=True, max_length=100, null=True)),
                ('targetTable', models.CharField(blank=True, max_length=100, null=True)),
                ('targetId', models.CharField(blank=True, max_length=100, null=True)),
                ('isRead', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
