# Generated by Django 5.2.3 on 2025-07-09 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructorId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employmentType', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAvailability',
            fields=[
                ('availabilityId', models.AutoField(primary_key=True, serialize=False)),
                ('dayOfWeek', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorExperience',
            fields=[
                ('experienceId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('isSubjectRelated', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Work Experience', 'Work Experience'), ('Award', 'Award'), ('Certification', 'Certification'), ('Research', 'Research')], max_length=30)),
                ('documentUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingHistory',
            fields=[
                ('teachingId', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('Summer', 'Summer')], max_length=10)),
                ('schoolYear', models.CharField(max_length=20)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor')),
            ],
        ),
    ]
