# Generated by Django 5.2.3 on 2025-07-18 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_role_remove_user_role_user_roles'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAbsence',
            fields=[
                ('absenceId', models.AutoField(primary_key=True, serialize=False)),
                ('reportType', models.CharField(choices=[('auto-detected', 'Auto Detected'), ('manual', 'Manual')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('dateMissed', models.DateField()),
                ('reportedAt', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.schedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAvailability',
            fields=[
                ('availabilityId', models.AutoField(primary_key=True, serialize=False)),
                ('dayOfWeek', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorCredentials',
            fields=[
                ('credentialId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Certification', 'Certification'), ('Workshop', 'Workshop'), ('Training', 'Training'), ('License', 'License')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isVerified', models.BooleanField(default=False)),
                ('documentUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('dateEarned', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
                ('relatedSubjects', models.ManyToManyField(blank=True, to='scheduling.subject')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorExperience',
            fields=[
                ('experienceId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Work Experience', 'Work Experience'), ('Academic Position', 'Academic Position'), ('Research Role', 'Research Role')], max_length=30)),
                ('isVerified', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
                ('relatedSubjects', models.ManyToManyField(blank=True, to='scheduling.subject')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorSubjectPreference',
            fields=[
                ('preferenceId', models.AutoField(primary_key=True, serialize=False)),
                ('preferenceType', models.CharField(choices=[('Prefer', 'Prefer'), ('Neutral', 'Neutral'), ('Avoid', 'Avoid')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingHistory',
            fields=[
                ('teachingId', models.AutoField(primary_key=True, serialize=False)),
                ('timesTaught', models.PositiveIntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduling.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject')),
            ],
        ),
    ]
