# Generated by Django 5.2.3 on 2025-07-15 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_remove_user_role_user_roles'),
        ('instructors', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAbsence',
            fields=[
                ('absenceId', models.AutoField(primary_key=True, serialize=False)),
                ('reportType', models.CharField(choices=[('auto-detected', 'Auto Detected'), ('manual', 'Manual')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('dateMissed', models.DateField()),
                ('reportedAt', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.schedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.subject')),
            ],
        ),
    ]
