# Generated by Django 5.2.3 on 2025-07-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_remove_user_role_user_roles'),
        ('instructors', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachinghistory',
            unique_together={('instructor', 'subject', 'semester')},
        ),
    ]
