# Generated by Django 5.2.3 on 2025-07-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_alter_teachinghistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorsubjectpreference',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
