# Generated by Django 5.2.3 on 2025-07-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_alter_instructorrank_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructordesignation',
            options={'ordering': ['designationId']},
        ),
        migrations.RemoveField(
            model_name='instructordesignation',
            name='otherAssignmentHours',
        ),
        migrations.RemoveField(
            model_name='instructordesignation',
            name='overloadBaccalaureate',
        ),
        migrations.RemoveField(
            model_name='instructordesignation',
            name='overloadDoctoral',
        ),
        migrations.RemoveField(
            model_name='instructordesignation',
            name='overloadMasters',
        ),
        migrations.RemoveField(
            model_name='instructordesignation',
            name='totalHours',
        ),
        migrations.AddIndex(
            model_name='instructordesignation',
            index=models.Index(fields=['name'], name='instructors_name_312990_idx'),
        ),
    ]
