# Generated by Django 5.2.3 on 2025-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_instructorsubjectpreference_updatedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorexperience',
            old_name='type',
            new_name='experienceType',
        ),
        migrations.AddField(
            model_name='instructorexperience',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
