# Generated by Django 5.2.3 on 2025-07-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_alter_instructordesignation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAcademicAttainment',
            fields=[
                ('attainmentId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('overloadHours', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['attainmentId'],
                'indexes': [models.Index(fields=['name'], name='instructors_name_b6593b_idx')],
            },
        ),
    ]
