# Generated by Django 5.2.3 on 2025-07-19 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_rename_type_instructorexperience_experiencetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructoravailability',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachinghistory',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
