# Generated by Django 5.2.3 on 2025-07-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_instructoracademicattainment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructoracademicattainment',
            old_name='overloadHours',
            new_name='overloadUnits',
        ),
    ]
