# Generated by Django 5.2.3 on 2025-07-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_rename_overloadhours_instructoracademicattainment_overloadunits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructoracademicattainment',
            old_name='overloadUnits',
            new_name='overloadHasDesignation',
        ),
        migrations.AddField(
            model_name='instructoracademicattainment',
            name='overloadNoDesignation',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
