# Generated by Django 5.2.3 on 2025-07-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_instructoravailability_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcredentials',
            name='issuer',
            field=models.CharField(default='PLAVEHOLDER', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorcredentials',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
