# Generated by Django 5.2.3 on 2025-07-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_rename_overloadunits_instructoracademicattainment_overloadhasdesignation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructoracademicattainment',
            old_name='overloadHasDesignation',
            new_name='overloadUnitsHasDesignation',
        ),
        migrations.RenameField(
            model_name='instructoracademicattainment',
            old_name='overloadNoDesignation',
            new_name='overloadUnitsNoDesignation',
        ),
    ]
