# Generated by Django 5.2.3 on 2025-07-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0007_rename_overloadhasdesignation_instructoracademicattainment_overloadunitshasdesignation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorexperience',
            name='experienceType',
            field=models.CharField(choices=[('Academic Position', 'Academic Position'), ('Work Experience', 'Work Experience'), ('Research Role', 'Research Role'), ('Administrative Role', 'Administrative Role'), ('Extension Service', 'Extension Service'), ('Consultancy', 'Consultancy')], max_length=30),
        ),
    ]
