# Generated by Django 5.2.3 on 2025-07-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0008_alter_instructorexperience_experiencetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorcredentials',
            name='type',
            field=models.CharField(choices=[('License', 'License'), ('Certification', 'Certification'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Training', 'Training'), ('Short Course', 'Short Course')], max_length=30),
        ),
    ]
