# Generated by Django 5.2.3 on 2025-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_remove_user_role_user_roles'),
        ('instructors', '0008_alter_instructorsubjectpreference_unique_together_and_more'),
        ('scheduling', '0012_alter_subject_defaultterm_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructorexperience',
            unique_together={('instructor', 'title', 'organization', 'startDate')},
        ),
        migrations.AddIndex(
            model_name='instructorexperience',
            index=models.Index(fields=['instructor', 'isVerified'], name='instructors_instruc_9d96bd_idx'),
        ),
    ]
