# Generated by Django 5.2.3 on 2025-07-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instructor_academicattainment'),
        ('instructors', '0009_alter_instructorcredentials_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorcredentials',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.instructor'),
        ),
        migrations.AlterField(
            model_name='instructorexperience',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.instructor'),
        ),
        migrations.AlterField(
            model_name='instructorsubjectpreference',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.instructor'),
        ),
    ]
