# Generated by Django 5.2.3 on 2025-08-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_instructor_normalload_and_more'),
        ('instructors', '0010_alter_instructorcredentials_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructoravailability',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.instructor'),
        ),
    ]
