# Generated by Django 5.2.3 on 2025-07-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_remove_user_role_user_roles'),
        ('instructors', '0010_alter_instructoravailability_unique_together_and_more'),
        ('scheduling', '0012_alter_subject_defaultterm_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teachinghistory',
            index=models.Index(fields=['instructor', 'subject', 'semester'], name='instructors_instruc_5944de_idx'),
        ),
    ]
