# Generated by Django 5.2.3 on 2025-07-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0011_teachinghistory_instructors_instruc_5944de_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorcredentials',
            options={'ordering': ['-dateEarned']},
        ),
    ]
