# Generated by Django 5.2.3 on 2025-07-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0012_alter_instructorcredentials_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorsubjectpreference',
            options={'ordering': ['instructor', 'subject']},
        ),
    ]
