# Generated by Django 5.2.3 on 2025-07-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0014_instructordesignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorRank',
            fields=[
                ('rankId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('University Professor', 'University Professor'), ('Professor I-VI', 'Professor I-VI'), ('Associate Professor I-V', 'Associate Professor I-V'), ('Assistant Professor I-IV', 'Assistant Professor I-IV'), ('Instructor I-III', 'Instructor I-III')], max_length=100, unique=True)),
                ('instructionHours', models.IntegerField(default=0)),
                ('researchHours', models.IntegerField(default=0)),
                ('extensionHours', models.IntegerField(default=0)),
                ('productionHours', models.IntegerField(default=0)),
                ('consultationHours', models.IntegerField(default=0)),
                ('otherAssignmentHours', models.IntegerField(default=0)),
                ('overloadDoctoral', models.IntegerField(default=9)),
                ('overloadMasters', models.IntegerField(default=6)),
                ('overloadBaccalaureate', models.IntegerField(default=6)),
                ('totalHours', models.IntegerField(default=40)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='instructors_name_ef585f_idx')],
            },
        ),
    ]
