# Generated by Django 5.2.3 on 2025-07-21 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instructor_designation_instructor_rank'),
        ('instructors', '0015_instructorrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachinghistory',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachingHistory', to='core.instructor'),
        ),
    ]
