# Generated by Django 5.2.3 on 2025-07-22 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0016_alter_teachinghistory_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructoravailability',
            options={'ordering': ['instructor', 'dayOfWeek', 'startTime']},
        ),
        migrations.AlterField(
            model_name='teachinghistory',
            name='timesTaught',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
