# Generated by Django 5.2.3 on 2025-08-11 02:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalStartTime', models.TimeField(default=datetime.time(8, 0))),
                ('normalEndTime', models.TimeField(default=datetime.time(17, 0))),
                ('overtimeEndTime', models.TimeField(default=datetime.time(20, 0))),
                ('allowWeekends', models.BooleanField(default=True)),
                ('maxSectionsPerSubject', models.IntegerField(default=5)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxClassesPerInstructorPerDay', models.IntegerField(default=4)),
                ('maxClassesPerInstructorPerWeek', models.IntegerField(default=20)),
                ('roomsPerTimeslotLimit', models.IntegerField(default=1)),
                ('minBreakBetweenClasses', models.IntegerField(default=1)),
                ('enforceRoomCapacity', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.semester')),
            ],
            options={
                'verbose_name': 'Schedule Constraint',
                'verbose_name_plural': 'Schedule Constraints',
                'unique_together': {('semester',)},
            },
        ),
    ]
