# Generated by Django 5.2.3 on 2025-12-15 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='idle', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('process_pid', models.IntegerField(blank=True, null=True)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
